from typing import Any, List, Optional, Union, Literal as TypingLiteral
from dataclasses import dataclass, field
from dataclasses_json import dataclass_json, config

# NOTE: This file is autogenerated from specification. Do not modify directly.

@dataclass_json
@dataclass
class Meta:
    isConstructor: bool = False
    isAsync: bool = False
    decorators: Optional['Identifier'] = None
    parameterKind: Optional[str] = None

@dataclass_json
@dataclass
class SourceLocation:
    start: 'Position' = None
    end: 'Position' = None
    sourcefile: str = None

@dataclass_json
@dataclass
class Position:
    line: int
    column: int

@dataclass_json
@dataclass
class BaseNode:
    loc: Optional[SourceLocation]
    _meta: Meta
    type: str = field(init=False)

    def __post_init__(self):
        self.type = self.__class__.__name__

@dataclass_json
@dataclass
class Noop(BaseNode):
    pass

@dataclass_json
@dataclass
class Literal(BaseNode):
    value: Union[None, int, str, bool]
    literalType: TypingLiteral["null", "number", "string", "boolean"]

@dataclass_json
@dataclass
class Identifier(BaseNode):
    name: str

@dataclass_json
@dataclass
class CompileUnit(BaseNode):
    body: List['Instruction']
    language: TypingLiteral["javascript", "typescript", "java", "golang", "python"]
    uri: str
    version: str
    languageVersion: Optional[Union[int, str, bool]] = None

@dataclass_json
@dataclass
class ExportStatement(BaseNode):
    argument: 'Expression'
    alias: 'Identifier'

@dataclass_json
@dataclass
class IfStatement(BaseNode):
    test: 'Expression'
    consequent: 'Instruction'
    alternative: Optional['Instruction'] = None

@dataclass_json
@dataclass
class SwitchStatement(BaseNode):
    discriminant: 'Expression'
    cases: List['CaseClause']

@dataclass_json
@dataclass
class CaseClause(BaseNode):
    body: 'Instruction'
    test: Optional['Expression'] = None

@dataclass_json
@dataclass
class ForStatement(BaseNode):
    body: 'Instruction'
    init: Optional[Union['Expression', 'VariableDeclaration']] = None
    test: Optional['Expression'] = None
    update: Optional['Expression'] = None

@dataclass_json
@dataclass
class WhileStatement(BaseNode):
    test: 'Expression'
    body: 'Instruction'
    isPostTest: Optional[bool] = False

@dataclass_json
@dataclass
class RangeStatement(BaseNode):
    right: 'Expression'
    body: 'Instruction'
    key: Optional[Union['VariableDeclaration', 'Expression']] = None
    value: Optional[Union['VariableDeclaration', 'Expression']] = None

@dataclass_json
@dataclass
class LabeledStatement(BaseNode):
    body: 'Instruction'
    label: Optional['Identifier'] = None

@dataclass_json
@dataclass
class ReturnStatement(BaseNode):
    argument: Optional['Expression'] = None
    isYield: Optional[bool] = False

@dataclass_json
@dataclass
class BreakStatement(BaseNode):
    label: Optional['Identifier'] = None

@dataclass_json
@dataclass
class ContinueStatement(BaseNode):
    label: Optional['Identifier'] = None

@dataclass_json
@dataclass
class ThrowStatement(BaseNode):
    argument: Optional['Expression'] = None

@dataclass_json
@dataclass
class TryStatement(BaseNode):
    body: 'Statement'
    handlers: Optional[List['CatchClause']] = None
    finalizer: Optional['Instruction'] = None

@dataclass_json
@dataclass
class CatchClause(BaseNode):
    parameter: List[Union['VariableDeclaration', 'Sequence']]
    body: 'Instruction'

@dataclass_json
@dataclass
class ExpressionStatement(BaseNode):
    expression: 'Expression'

@dataclass_json
@dataclass
class ScopedStatement(BaseNode):
    body: List['Instruction']
    id: Optional['Identifier'] = None

@dataclass_json
@dataclass
class BinaryExpression(BaseNode):
    operator: TypingLiteral["+", "-", "*", "/", "**", "%", "<<", ">>", ">>>", "<<<", "&&", "||", ",,", "&", ",", "^", "<", ">", "<=", ">=", "==", "!=", "|", "instanceof", "in", "push", "===", "!==", "??"]
    left: 'Expression'
    right: 'Expression'

@dataclass_json
@dataclass
class UnaryExpression(BaseNode):
    operator: TypingLiteral["-", "+", "++", "--", "~", "delete", "!", "typeof", "void"]
    argument: 'Expression'
    isSuffix: Optional[bool] = True

@dataclass_json
@dataclass
class AssignmentExpression(BaseNode):
    left: 'LVal'
    right: 'Expression'
    operator: TypingLiteral["=", "^=", "&=", "<<=", ">>=", ">>>=", "+=", "-=", "*=", "/=", "%=", "|=", "**="]
    cloned: Optional[bool] = None

@dataclass_json
@dataclass
class Sequence(BaseNode):
    expressions: List['Instruction']

@dataclass_json
@dataclass
class CastExpression(BaseNode):
    expression: 'Expression'
    as_: 'Type' = field(metadata=config(field_name='as'))

@dataclass_json
@dataclass
class ConditionalExpression(BaseNode):
    test: 'Expression'
    consequent: 'Expression'
    alternative: 'Expression'

@dataclass_json
@dataclass
class SuperExpression(BaseNode):
    pass

@dataclass_json
@dataclass
class ThisExpression(BaseNode):
    pass

@dataclass_json
@dataclass
class MemberAccess(BaseNode):
    object: 'Expression'
    property: 'Expression'
    computed: Optional[bool] = False

@dataclass_json
@dataclass
class SliceExpression(BaseNode):
    start: Optional['Instruction'] = None
    end: Optional['Instruction'] = None
    step: Optional['Instruction'] = None

@dataclass_json
@dataclass
class TupleExpression(BaseNode):
    elements: List[Union['Expression', 'Instruction']]
    modifiable: Optional[bool] = None

@dataclass_json
@dataclass
class ObjectExpression(BaseNode):
    properties: List[Union['ObjectProperty', 'SpreadElement']]
    id: Optional['Identifier'] = None

@dataclass_json
@dataclass
class ObjectProperty(BaseNode):
    key: 'Expression'
    value: Union[None, 'Expression']

@dataclass_json
@dataclass
class CallExpression(BaseNode):
    callee: 'Expression'
    arguments: List['Expression']

@dataclass_json
@dataclass
class NewExpression(BaseNode):
    callee: 'Expression'
    arguments: List['Expression']

@dataclass_json
@dataclass
class FunctionDefinition(BaseNode):
    parameters: List['VariableDeclaration']
    returnType: 'Type'
    body: 'Instruction'
    id: Optional['Expression'] = None
    modifiers: Optional[List[str]] = None

@dataclass_json
@dataclass
class ClassDefinition(BaseNode):
    body: List['Instruction']
    supers: List['Expression']
    id: Optional['Identifier'] = None

@dataclass_json
@dataclass
class VariableDeclaration(BaseNode):
    id: 'LVal'
    varType: 'Type'
    init: Optional['Expression'] = None
    cloned: Optional[bool] = None
    variableParam: Optional[bool] = False

@dataclass_json
@dataclass
class DereferenceExpression(BaseNode):
    argument: 'Expression'

@dataclass_json
@dataclass
class ReferenceExpression(BaseNode):
    argument: 'Expression'

@dataclass_json
@dataclass
class ImportExpression(BaseNode):
    from_: 'Literal' = field(metadata=config(field_name='from'))
    local: Optional['Identifier'] = None
    imported: Optional[Union['Identifier', 'Literal']] = None

@dataclass_json
@dataclass
class SpreadElement(BaseNode):
    argument: 'Expression'

@dataclass_json
@dataclass
class YieldExpression(BaseNode):
    argument: Optional['Expression'] = None

@dataclass_json
@dataclass
class PackageDeclaration(BaseNode):
    packageName: 'Expression'

@dataclass_json
@dataclass
class PrimitiveType(BaseNode):
    kind: TypingLiteral["string", "number", "boolean", "null"]
    id: Optional['Identifier'] = "PrimitiveType"
    typeArguments: Optional[List['Type']] = None

@dataclass_json
@dataclass
class ArrayType(BaseNode):
    element: 'Type'
    id: Optional['Identifier'] = "ArrayType"
    typeArguments: Optional[List['Type']] = None
    size: Optional['Expression'] = None

@dataclass_json
@dataclass
class PointerType(BaseNode):
    id: 'Identifier'
    element: 'Type'
    kind: TypingLiteral["pointer", "reference"]
    typeArguments: Optional[List['Type']] = None

@dataclass_json
@dataclass
class MapType(BaseNode):
    keyType: 'Type'
    valueType: 'Type'
    id: Optional['Identifier'] = "MapType"
    typeArguments: Optional[List['Type']] = None

@dataclass_json
@dataclass
class ScopedType(BaseNode):
    id: Optional['Identifier'] = None
    scope: Optional[Union[None, 'Type']] = None
    typeArguments: Optional[List['Type']] = None

@dataclass_json
@dataclass
class TupleType(BaseNode):
    id: 'Identifier'
    elements: List['Type']
    typeArguments: Optional[List['Type']] = None

@dataclass_json
@dataclass
class ChanType(BaseNode):
    id: 'Identifier'
    dir: str
    valueType: 'Type'

@dataclass_json
@dataclass
class FuncType(BaseNode):
    id: 'Identifier'
    typeParams: List['Type']
    params: List['Type']
    results: List['Type']

@dataclass_json
@dataclass
class DynamicType(BaseNode):
    id: Optional['Identifier'] = None
    typeArguments: Optional[List['Type']] = None

@dataclass_json
@dataclass
class VoidType(BaseNode):
    id: Optional['Identifier'] = None
    typeArguments: Optional[List['Type']] = None

Conditional = Union[
    IfStatement,
    SwitchStatement,
    ConditionalExpression
]

Declaration = Union[
    FunctionDefinition,
    ClassDefinition,
    VariableDeclaration,
    PackageDeclaration
]

Expression = Union[
    Noop,
    Literal,
    Identifier,
    SwitchStatement,
    ReturnStatement,
    BinaryExpression,
    UnaryExpression,
    AssignmentExpression,
    Sequence,
    CastExpression,
    ConditionalExpression,
    SuperExpression,
    ThisExpression,
    MemberAccess,
    SliceExpression,
    TupleExpression,
    ObjectExpression,
    ObjectProperty,
    CallExpression,
    NewExpression,
    FunctionDefinition,
    ClassDefinition,
    VariableDeclaration,
    DereferenceExpression,
    ReferenceExpression,
    ImportExpression,
    SpreadElement,
    YieldExpression,
    PackageDeclaration
]

Instruction = Union[
    Noop,
    Literal,
    Identifier,
    ExportStatement,
    IfStatement,
    SwitchStatement,
    ForStatement,
    WhileStatement,
    RangeStatement,
    LabeledStatement,
    ReturnStatement,
    BreakStatement,
    ContinueStatement,
    ThrowStatement,
    TryStatement,
    CatchClause,
    ExpressionStatement,
    ScopedStatement,
    BinaryExpression,
    UnaryExpression,
    AssignmentExpression,
    Sequence,
    CastExpression,
    ConditionalExpression,
    SuperExpression,
    ThisExpression,
    MemberAccess,
    SliceExpression,
    TupleExpression,
    ObjectExpression,
    ObjectProperty,
    CallExpression,
    NewExpression,
    FunctionDefinition,
    ClassDefinition,
    VariableDeclaration,
    DereferenceExpression,
    ReferenceExpression,
    ImportExpression,
    SpreadElement,
    YieldExpression,
    PackageDeclaration
]

LVal = Union[
    Identifier,
    MemberAccess,
    TupleExpression
]

Loop = Union[
    ForStatement,
    WhileStatement,
    RangeStatement
]

Scopable = Union[
    WhileStatement,
    RangeStatement,
    CatchClause,
    ScopedStatement,
    FunctionDefinition,
    ClassDefinition
]

Standardized = Union[
    Noop,
    Literal,
    Identifier,
    CompileUnit,
    ExportStatement,
    IfStatement,
    SwitchStatement,
    CaseClause,
    ForStatement,
    WhileStatement,
    RangeStatement,
    LabeledStatement,
    ReturnStatement,
    BreakStatement,
    ContinueStatement,
    ThrowStatement,
    TryStatement,
    CatchClause,
    ExpressionStatement,
    ScopedStatement,
    BinaryExpression,
    UnaryExpression,
    AssignmentExpression,
    Sequence,
    CastExpression,
    ConditionalExpression,
    SuperExpression,
    ThisExpression,
    MemberAccess,
    SliceExpression,
    TupleExpression,
    ObjectExpression,
    ObjectProperty,
    CallExpression,
    NewExpression,
    FunctionDefinition,
    ClassDefinition,
    VariableDeclaration,
    DereferenceExpression,
    ReferenceExpression,
    ImportExpression,
    SpreadElement,
    YieldExpression,
    PackageDeclaration,
    PrimitiveType,
    ArrayType,
    PointerType,
    MapType,
    ScopedType,
    TupleType,
    ChanType,
    FuncType,
    DynamicType,
    VoidType
]

Statement = Union[
    Noop,
    ExportStatement,
    IfStatement,
    SwitchStatement,
    ForStatement,
    WhileStatement,
    RangeStatement,
    LabeledStatement,
    ReturnStatement,
    BreakStatement,
    ContinueStatement,
    ThrowStatement,
    TryStatement,
    ExpressionStatement,
    ScopedStatement,
    Sequence,
    FunctionDefinition,
    ClassDefinition,
    VariableDeclaration,
    YieldExpression,
    PackageDeclaration
]

Type = Union[
    Identifier,
    PrimitiveType,
    ArrayType,
    PointerType,
    MapType,
    ScopedType,
    TupleType,
    ChanType,
    FuncType,
    DynamicType,
    VoidType
]

Node = Union[
    ArrayType,
    AssignmentExpression,
    BinaryExpression,
    BreakStatement,
    CallExpression,
    CaseClause,
    CastExpression,
    CatchClause,
    ChanType,
    ClassDefinition,
    CompileUnit,
    ConditionalExpression,
    ContinueStatement,
    DereferenceExpression,
    DynamicType,
    ExportStatement,
    ExpressionStatement,
    ForStatement,
    FuncType,
    FunctionDefinition,
    Identifier,
    IfStatement,
    ImportExpression,
    LabeledStatement,
    Literal,
    MapType,
    MemberAccess,
    NewExpression,
    Noop,
    ObjectExpression,
    ObjectProperty,
    PackageDeclaration,
    PointerType,
    PrimitiveType,
    RangeStatement,
    ReferenceExpression,
    ReturnStatement,
    ScopedStatement,
    ScopedType,
    Sequence,
    SliceExpression,
    SpreadElement,
    SuperExpression,
    SwitchStatement,
    ThisExpression,
    ThrowStatement,
    TryStatement,
    TupleExpression,
    TupleType,
    UnaryExpression,
    VariableDeclaration,
    VoidType,
    WhileStatement,
    YieldExpression
]

