import base64
import os
import re
import time
import uuid
from ast import literal_eval
from collections import Counter
from concurrent.futures import ThreadPoolExecutor
from functools import wraps

import cv2
import numpy as np
import pandas as pd
import requests
from elasticsearch import Elasticsearch, helpers
from flask import current_app as app
from flask import g, Request, Flask
from flask import request, jsonify
from mysql.connector.cursor import MySQLCursor
from skimage.metrics import structural_similarity as ssim
from sklearn.cluster import HDBSCAN
from tqdm import tqdm

from src import aiutils
from src import safeutils
from src.db_pool import pool
from src.preprocessing_utils import replace_keyword



# the maximum number of tokens in the input
# MAX_INPUT_TOKENS = 200
MAX_INPUT_TOKENS = int(os.getenv('MAX_INPUT_TOKENS', 1000))
# the minimal similarity between the input and the document
MINIMAL_DOCUMENT_SIMILARITY = 0.75
# the minimal similarity between the input and the document for specific question(any product detected in the question)
MINIMAL_DOCUMENT_SIMILARITY_FOR_SPECIFIC_QUESTION = 0.65
ES_MODE = os.getenv('ES_MODE')
ES_QUERY_SIZE = int(os.getenv('ES_QUERY_SIZE'))


def get_table_name_by_tenant(tenant: str):
    if tenant == 'ALIPAYPLUS':
        temp_table_name = 'knowledge_base_temp'
    else:
        temp_table_name = f'{tenant.lower()}_knowledge_base_temp'
    table_name = temp_table_name.replace('_temp', '')
    return temp_table_name, table_name


def get_role_by_tenant(tenant: str):
    if tenant == 'ALIPAYPLUS':
        return ['MPP', 'ACQP']
    return [tenant]


def write_es(
        client: Elasticsearch,
        db_table: str,
        df: pd.DataFrame,
        batch_size: int
):
    """根据从MySQL读取的Dataframe将知识写入ES"""
    actions = [{
        '_index': db_table,
        '_id': kid,
        'title': title,
        'heading': heading,
        'category': category,
        'product': product,
        'sub_product': sub_product,
        'role': role,
        'content': content,
        'url': url,
        'features': [float(li) for li in features.split(",")],
        'document_version': version,
        'md5': md5,
        'operator': operator,
        'comments': comments,
        'source': source,
        'updated': updated,
        'to_be_inherited': to_be_inherited,
    } for
        _, kid, title, heading, category, product, sub_product, role, content, url, features, version, md5, operator, comments, source, updated, to_be_inherited
        in df.itertuples()]

    for i in tqdm(range(0, len(actions), batch_size)):
        start, end = i, i + batch_size - 1
        end = len(actions) if end > len(actions) else end
        helpers.bulk(client, actions[start:end + 1])


def generate_chat_id(request):
    # required: question, chat_id
    if not request.get_json() or "question" not in request.get_json() or "chat_id" not in request.get_json():
        return {"message": "question or chat_id not found."}, 400

    # chat_id is generated by the backend, hence the first question in a chat will not have chat_id
    # subsequent questions in the same chat will have the same chat_id
    chat_id = request.get_json()["chat_id"]
    # if the chat_id is empty, it's a new chat
    if chat_id == "":
        chat_id = str(uuid.uuid4().int)[:32]

    g.chat_id = chat_id

    return chat_id


def replace_keywords(request, username, keyword_replacement_dict):
    question_original = request.get_json()["question"]
    g.question_text = question_original

    # preprocess the question_original, but we still store the original question for internal debugging.
    if keyword_replacement_dict:
        question_original = replace_keyword(
            text=question_original,
            replacement_dict=keyword_replacement_dict
        )
    app.logger.debug(f"Keyword replaced question is {question_original}")

    # check the question length
    tokens_of_question = aiutils.num_tokens_from_string(question_original)
    if tokens_of_question > MAX_INPUT_TOKENS:
        g.status = "REJECTED"
        g.status_message = "QUESTION_TOO_LONG"
        return {"message": "Sorry, the question you asked might be too long. Please ask a shorter question.",
                "chat_id": g.chat_id}, 400

    app.logger.info("original question: " + question_original)
    # the question should only contain chinese, english, number, and special characters

    is_vaild = safeutils.check_input_only_contain_CNandEN(question_original)
    if not is_vaild:
        app.logger.warning(
            "user: " + username + " is asking question other than CN/EN : " + question_original)
        g.status = "REJECTED"
        g.status_message = "INVALID_CHARACTERS"
        raise Exception("INVALID_CHARACTERS")

    return question_original


def check_question_length_and_language(question_original, username):
    g.question_text = question_original

    # check if the question is empty
    if not question_original:
        g.status = "REJECTED"
        g.status_message = "EMPTY_QUESTION"
        raise Exception('EMPTY_QUESTION')

    # check the question length
    tokens_of_question = aiutils.num_tokens_from_string(question_original)
    if tokens_of_question > MAX_INPUT_TOKENS:
        g.status = "REJECTED"
        g.status_message = "QUESTION_TOO_LONG"
        raise Exception('QUESTION_TOO_LONG')

    app.logger.info("original question: " + question_original)
    # the question should only contain chinese, english, number, and special characters

    is_valid = safeutils.check_input_only_contain_CNandEN(question_original)
    if not is_valid:
        app.logger.warning(
            "user: " + username + " is asking question other than CN/EN : " + question_original)
        g.status = "REJECTED"
        g.status_message = "INVALID_CHARACTERS"
        raise Exception("INVALID_CHARACTERS")

    return question_original


# 检查敏感信息
def check_sensitive_info(question_original, username, app, is_remittance=False):
    # OPENAI检查敏感信息
    is_sensitive = check_question_by_moderation(
        question_original, username, app)

    # info_sec检查敏感信息
    is_passed_by_infosec = info_sec_check(question_original, username, app, is_remittance=is_remittance)

    # 两个都通过表示检查通过
    return is_sensitive and is_passed_by_infosec


def check_question_by_moderation(question_original, username, app):
    try:
        start_time = time.time()
        is_sensitive, sensitive_types = safeutils.review_sensitivity(
            question_original)
        time_taken = time.time() - start_time
        app.logger.debug(
            f"Time taken to check review_sensitivity: {time_taken}")

        if is_sensitive:
            app.logger.warning(
                "user: " + username + " is asking sensitive question: " + question_original)
            app.logger.warning("sensitive types: " + str(sensitive_types))
            g.status = "REJECTED"
            g.status_message = "OPENAI_SENSITIVE_INFORMATION"
            return False

    except Exception as e:
        app.logger.error("check sensitive information error: " + str(e))
        # openAI connection error
        g.status = "REJECTED"
        g.status_message = "OPENAI_CONNECTION_ERROR"
        raise Exception("OPENAI_CONNECTION_ERROR")

    return True


def info_sec_check(question_original, username, app, is_remittance=False):
    start_time = time.time()
    is_passed_by_infosec, message_from_infosec = safeutils.info_security_check(
        query=question_original, answer=None, appScene='online_qna', username=username, is_remittance=is_remittance)
    time_taken = time.time() - start_time
    app.logger.debug(f"Time taken to check info_security_check: {time_taken}")
    app.logger.info("infosec check result: " + str(is_passed_by_infosec))

    if not is_passed_by_infosec:
        app.logger.warning(
            "user: " + username + " is asking question failed infosec check: " + question_original)
        g.status = "REJECTED"
        g.status_message = "INFOSEC_CHECK_QUESTION_FAILED"

    return is_passed_by_infosec


def llm_get_knowledge_check(answer: str, threshold: float = 0.9) -> bool:
    """
    Check whether the LLM has successfully found the relevant knowledge it needs

    Args:
        answer(str): the output of the LLM
        threshold(float): the threshold of similarity, default at 0.9

    Returns:
        bool: Whether the LLM has successfully found the relevant knowledge it needs
    """
    chinese = "对不起，我没有找到和您的问题相关的内容，请换一个问题，或者提供更详细的细节。"
    english = "I'm sorry, but I can't find the information you're asking for in the Alipay+ documents. " \
              "Could you please provide more details or check another source?"

    answer_embedding = aiutils.compute_text_embedding(answer)
    chinese_embedding = aiutils.compute_text_embedding(chinese)
    english_embedding = aiutils.compute_text_embedding(english)

    if aiutils.is_chinese(answer):
        similarity = aiutils.vector_similarity(answer_embedding, chinese_embedding)
    else:
        similarity = aiutils.vector_similarity(answer_embedding, english_embedding)

    app.logger.info(f"Answer similarity (GPT_FOUND_NO_KNOWLEDGE): {similarity}")

    if similarity >= threshold:
        return False
    return True


def set_ams_product(request):
    sub_product = set()

    try:
        # product and scneario are in same meaning
        request_product = request.get_json()["product"]
        if len(request_product) == 0:
            product = ["ALL"]
        else:

            GOL = ['Checkout Payment', 'Auto debit',
                   'Easy pay', 'Scan To Bind', 'Subscription']
            gol_sub_product = {
                "Checkout Payment": ['Payment'],
                "Auto debit": ['Authorization', 'Payment'],
                "Easy pay": ['Payment'],
                "Scan To Bind": ['Authorization', 'Payment'],
                "Subscription": ['Subscription'],
            }

            GOF = ['User-Presented Mode Payment',
                   'Order Code Payment', 'Entry Code Payment']

            gof_sub_product = {
                "User-Presented Mode Payment": ['Payment', 'Refund', 'Registration'],
                "Order Code Payment": ['Payment', 'Refund', 'Registration'],
                "Entry Code Payment": ['Payment', 'Refund', 'Registration']
            }

            product = set()
            for p in request_product:
                if p in GOL:
                    product.add("GOL")
                if p in GOF:
                    product.add("GOF")
            product.add("ALL")

            for p in request_product:
                if gol_sub_product.get(p):
                    for p1 in gol_sub_product.get(p):
                        sub_product.add(p1)
                if gof_sub_product.get(p):
                    for p1 in gof_sub_product.get(p):
                        sub_product.add(p1)

    except KeyError:
        product = ["ALL"]

    product = list(product)
    sub_product = list(sub_product)

    return product, sub_product


def set_role_product_version(
        request: Request,
        app: Flask,
        version_list: pd.DataFrame,
        is_pds: bool = False,
        is_mini: bool = False,
        is_remittance: bool = False,
):
    role = request.json.get('role')  # [SOURCE]
    if not role:
        if is_pds:
            role = 'PDS'
        elif is_mini:
            role = 'MINI'
        elif is_remittance:
            role = 'REMITTANCE'
        else:  # Alipay+ or AMS
            role = "ACQP"

    # product and scenario are in same meaning
    product = request.json.get('product', [])  # [SOURCE]
    if len(product) == 0:
        product = ["ALL"]
    else:
        product.append("ALL")

    if "MPM" in product:
        product.append("private_order_code")
        product.append("order_code")
        product.append("entry_code")
    app.logger.info(f"selected products: {product}")

    version = request.json.get('version')  # [SOURCE]
    if not version:
        version = version_list.loc[role]["version"]

    return role, product, version


def visiting_url_and_product_detected(request, app, question_original, product, username, chat_id):
    visiting_url = request.get_json(
    )["visiting_url"] if "visiting_url" in request.get_json() else ""
    start_time = time.time()
    visiting_products = aiutils.product_detect_from_visiting(visiting_url)

    time_taken = time.time() - start_time
    app.logger.debug(
        f"Time taken to run product_detect_from_visiting: {time_taken}")
    app.logger.info("visiting products: " + str(visiting_products))

    start_time = time.time()
    detected_products = aiutils.scenario_detect(question_original)
    time_taken = time.time() - start_time
    app.logger.debug(f"Time taken to run scenario_detect: {time_taken}")
    app.logger.info("detected products: " + str(detected_products))
    # add the products detected
    [product.append(x) for x in detected_products if x not in product]
    app.logger.info(
        "username: " + username + ", question: " + question_original +
        ", chat_id: " + str(chat_id) + ", product: " + str(product) + ", visiting_url: " + str(
            visiting_url))

    return detected_products


def get_similar_question_clustering(df, top_k=None):
    """
    Get similar question clustering

    Args:
        df(pd.DataFrame): the dataframe read from the sql query
        top_k(int | None): return the top k results

    Returns:
        list[tuple[list[tuple[str, int]], int]]: a list of tuples contain similar question clustering and the count

    Examples:
        Return: [([('hello', 8), ('你好', 1), ('Hello', 1)], 10),...]
    """
    # similar_questions_with_count = []
    try:
        df["embedding"] = df.embedding.apply(literal_eval).apply(np.array)  # convert string to numpy array
        matrix = np.vstack(df.embedding.values)

        # Use HDBSCAN for clustering
        hdb = HDBSCAN(min_samples=3, min_cluster_size=3)
        hdb.fit(matrix)

        df['cluster'] = hdb.labels_
        df = df.query('cluster != -1')

        question_clusters = []
        for c in df.cluster.unique():
            question_clusters.append(df.query(f'cluster == {c}').question.to_list())

        # Sort similar questions by question count
        similar_questions = [Counter(cluster).most_common() for cluster in question_clusters]
        similar_questions_with_count = sorted(
            [(questions, sum([num for _, num in questions])) for questions in similar_questions],
            key=lambda x: x[1],
            reverse=True
        )
    except Exception as e:
        app.logger.error(f"error when fetching similar questions: {e}")
        return None
    # finally:
    #     conn.close()

    if top_k:
        return similar_questions_with_count[:top_k]
    return similar_questions_with_count


def find_record_by_chat_id(chat_id):
    # if the question is not empty, check the chat_id is valid or not
    record = None
    if chat_id and chat_id != '':
        # handle the connection gracefully
        app.logger.info(f"used_connection:{pool.get_used_connection_count()}")
        try:
            con = pool.get_connection()
            cur: MySQLCursor = con.cursor(buffered=True)
            # fetch the chat_id and product_belongs_to from log_questions table
            # chat_id is used to detect and identify same dialogue and product_belongs_to is used to identify the scenario of the question
            cur.execute(
                'select chat_id, prompt, answer, product_belongs_to, role from log_questions where chat_id = %s',
                [chat_id])
            # fetch the latest record
            # if the chat_id is not found, the record will be None
            if cur.rowcount > 0:
                record = cur.fetchall()[-1]
        except Exception as e:
            app.logger.error("error when fetching the chat_id: " + str(e))
        finally:
            con.close()
    return record


def find_ams_record_by_chat_id(chat_id):
    # if the question is not empty, check the chat_id is valid or not
    record = None
    if chat_id and chat_id != '':
        # handle the connection gracefully
        app.logger.info(f"used_connection:{pool.get_used_connection_count()}")
        try:
            con = pool.get_connection()
            cur = con.cursor(buffered=True)
            # fetch the chat_id and product_belongs_to from log_questions table
            # chat_id is used to detect and identify same dialogue and product_belongs_to is used to identify the scenario of the question
            cur.execute(
                'select chat_id, prompt, answer, product_belongs_to from ams_log_questions_v2 where chat_id = %s',
                [chat_id])
            # fetch the latest record
            # if the chat_id is not found, the record will be None
            if cur.rowcount > 0:
                record = cur.fetchall()[-1]
        except Exception as e:
            app.logger.error("error when fetching the chat_id: " + str(e))
        finally:
            con.close()
    return record


def find_relevant_knowledge(
        detected_products: list,
        question_original: str,
        filtered_document_embeddings: dict,
        es_mode=ES_MODE,
        *args, **kwargs
):
    """
    Find relevant knowledge from the knowledge base

    Args:
        detected_products(list): the detected products
        question_original(str): the question
        filtered_document_embeddings(dict): the filtered document embeddings
        es_mode(str): the mode of Elasticsearch, supports 'none', 'hybrid', 'bm25' and 'cos_sim'

    Returns:
        Relevant knowledge
    """
    query_for_doc_retrieval = kwargs.get('query_for_doc_retrieval')
    db_table = kwargs.get('db_table')
    role = kwargs.get('role')
    version = kwargs.get('version')
    robot_type = kwargs.get('robot_type', 'DocsAI')
    es_query_size = kwargs.get('es_query_size')

    if es_mode == 'none':
        if len(detected_products) > 0:
            relevant_knowledge = aiutils.order_document_sections_by_query_similarity(
                question_original, filtered_document_embeddings, MINIMAL_DOCUMENT_SIMILARITY_FOR_SPECIFIC_QUESTION)
        else:
            relevant_knowledge = aiutils.order_document_sections_by_query_similarity(
                question_original, filtered_document_embeddings, MINIMAL_DOCUMENT_SIMILARITY)

        return relevant_knowledge
    else:
        return find_relevant_knowledge_by_es(
            query_for_doc_retrieval=query_for_doc_retrieval,
            db_table=db_table,
            role=role,
            version=version,
            mode=es_mode,
            robot_type=robot_type,
            es_query_size=es_query_size
        )


def find_relevant_knowledge_by_es(query_for_doc_retrieval, db_table, role, version, mode='hybrid', **kwargs):
    """
    Use Elasticsearch to query the knowledge base

    Args:
        query_for_doc_retrieval(str): the user question
        db_table(str): the knowledge base name
        role(str): the role, optional
        version(str): the version of the knowledge base
        mode(str): the search mode of Elasticsearch, supports 'hybrid', 'bm25', 'cos_sim'

    Returns:
        the knowledge
    """

    robot_type = kwargs.get('robot_type', 'DocsAI')
    documentation_title = kwargs.get('documentation_title')
    client = pool.es_client
    es_query_size = kwargs.get('es_query_size', ES_QUERY_SIZE)
    if documentation_title:
        es_query_size = 16
        mode = 'title_query'

    filter_condition = [
        {"term": {"role.keyword": role}},
        {"term": {"document_version.keyword": version}},
    ]
    if robot_type in ['Debugger', 'Code Generator']:
        filter_condition.append({
            "bool": {
                "should": [
                    {"match_phrase": {"title": "API Reference"}},
                    {"match_phrase": {"title": "SDK Reference"}}
                ]
            }
        })

    def execute_query(query):
        resp_es = client.search(
            index=db_table,
            _source=['title', 'url', 'content', 'features'],
            size=es_query_size,
            query=query,
            request_timeout=30,
        )
        return [
            (
                hit['_score'],
                int(hit['_id']),  # ES的_id字段只能是字符串，后端需要的是整数
                hit['_source']['title'],
                hit['_source']['url'],
                hit['_source']['content'],
                str(hit['_source']['features'])
            ) for hit in resp_es['hits']['hits']]

    def bm25():
        query = {
            "bool": {
                "filter": filter_condition,
                "must": {
                    "match": {
                        "content": query_for_doc_retrieval
                    }
                }
            }
        }
        return execute_query(query)

    def cos_sim():
        query = {
            "script_score": {
                "query": {
                    "bool": {
                        "filter": filter_condition,
                        "must": {"match_all": {}}
                    }
                },
                "script": {
                    "source": "cosineSimilarity(params.query_vector, 'features')",
                    "params": {
                        "query_vector": aiutils.compute_text_embedding(query_for_doc_retrieval)
                    }
                }
            }
        }
        return execute_query(query)

    def title_query():
        query = {
            'bool': {
                'filter': filter_condition,
                'must': {
                    "match_phrase": {
                        "title": documentation_title
                    }
                }
            }
        }
        return execute_query(query)

    start_time = time.time()

    if mode == 'hybrid':
        results = list(set(bm25() + cos_sim()))
    elif mode == 'bm25':
        results = bm25()
    elif mode == 'cos_sim':
        results = cos_sim()
    elif mode == 'title_query':
        results = title_query()
    else:
        raise ValueError(
            f'The ES search mode `{mode}` is not supported yet, please choose one from `hybrid`, `bm25`, `cos_sim` and `api_query`.')

    end_time = time.time()
    # print(f'Time taken to ESDb to get knowledge: {end_time - start_time}s')
    app.logger.debug(f'Time taken to ESDb to get knowledge: {end_time - start_time}s')
    return results


def extract_keyframes(video_path, output_dir, ssim_threshold=0.95):
    """Extract keyframes from a video"""
    start_time = time.time()
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    cap = cv2.VideoCapture(video_path)
    prev_frame = None
    frame_count = 0
    keyframe_count = 0

    app.logger.info(f'Extracting keyframes from video `{video_path}`...')
    while True:
        ret, frame = cap.read()
        if not ret:
            break

        gray_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

        if prev_frame is None:
            prev_frame = gray_frame
            keyframe_path = os.path.join(output_dir, f"keyframe_{keyframe_count:04d}.png")
            cv2.imwrite(keyframe_path, frame)
            keyframe_count += 1
            continue

        score = ssim(prev_frame, gray_frame)

        if score < ssim_threshold:
            keyframe_path = os.path.join(output_dir, f"keyframe_{keyframe_count:04d}.png")
            cv2.imwrite(keyframe_path, frame)
            keyframe_count += 1

        prev_frame = gray_frame
        frame_count += 1

    cap.release()
    end_time = time.time()
    app.logger.info(
        f"Extracted {keyframe_count} keyframes from {frame_count} frames. Saved to '{output_dir}'. Time taken: {(end_time - start_time):.2f} seconds.")


def extract_frames(video_path: str, interval=0.5):
    """
    Extract frames by specified interval from a video
    """
    video = cv2.VideoCapture(video_path)

    # Get the frames per second of the video
    fps = video.get(cv2.CAP_PROP_FPS)
    app.logger.info(f"Frames per second: {fps}")

    # Set the interval for saving frames (in seconds)
    next_frame_time = 0.0
    frame_extracted = 0

    while video.isOpened():
        success, frame = video.read()
        if not success:
            break

        # Get the current position of the video file in milliseconds
        current_time = video.get(cv2.CAP_PROP_POS_MSEC) / 1000.0

        # If the current time is greater than or equal to the next frame time, save the frame
        if current_time >= next_frame_time:
            yield frame
            next_frame_time += interval

            frame_extracted += 1

    video.release()
    app.logger.info(f'{frame_extracted} frames extracted.')


def compute_ssim(prev_frame, current_frame):
    """Calculate the structure similarity between two images"""
    return ssim(prev_frame, current_frame)


def deduplicate_frames(video_path: str, output_dir: str, ssim_threshold=0.95, num_threads=4):
    """De-duplicate frames from a video"""
    start_time = time.time()
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    frames = []
    frame_count, keyframe_count = 0, 0
    for frame in extract_frames(video_path):
        gray_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        frames.append((frame_count, gray_frame, frame))
        frame_count += 1

    with ThreadPoolExecutor(max_workers=num_threads) as executor:
        futures = []
        for i in range(0, len(frames)):
            prev_frame = frames[i - 1][1]
            current_frame = frames[i][1]
            futures.append(executor.submit(compute_ssim, prev_frame, current_frame))

        for i, future in tqdm(enumerate(futures)):
            score = future.result()

            if score < ssim_threshold and (i + 1) < len(frames):
                keyframe_path = os.path.join(output_dir, f"keyframe_{keyframe_count:04d}.png")
                cv2.imwrite(keyframe_path, frames[i + 1][2])
                keyframe_count += 1

    end_time = time.time()
    app.logger.info(
        f"Extracted {keyframe_count} keyframes from {frame_count} frames. Saved to '{output_dir}'. Time taken: {(end_time - start_time):.2f} seconds.")





def encode_image(image_path):
    """Encode the image to base64"""
    with open(image_path, "rb") as image_file:
        return base64.b64encode(image_file.read()).decode('utf-8')


# 编译正则表达式以提高匹配性能
SQL_INJECTION_PATTERNS = [
    # 常见的 SQL 注入关键字（' 或者 -- 注释等）
    re.compile(r"(?:')|(?:--)|(/\*(?:.|[\n\r])*?\*/)|(union\s+select)", re.IGNORECASE),
    # URL 编码的注入攻击，如 %27（单引号）%3D（等号）等
    re.compile(r"((\%27)+)|((\%25)+)|((\;)+)|(((\%3D)+))|((\-\-)+)", re.IGNORECASE),
    # URL 编码的特殊字符检测（: ; < = " ( ) + 等）
    re.compile(r"((\%3A)+)|((\%3B)+)|((\%3C)+)|((\%3D)+)|((\%20)+)|((\%22)+)|((\%28)+)|((\%29)+)|((\%2B)+)", re.IGNORECASE)
]

XSS_PATTERNS = [
    # 检测 <script> 标签的 XSS 注入
    re.compile(r"<script.*?>.*?</script>", re.IGNORECASE),
    # 检测 < 和 > 标签，防止 HTML 标签注入
    re.compile(r"(<|%3C).*?(/>|%3E)", re.IGNORECASE),
    # 检测常见的 JavaScript 警告框， 如 alert()
    re.compile(r"(alert\(.*?\))", re.IGNORECASE),
    # 检测 `javascript:` 协议注入
    re.compile(r"javascript:", re.IGNORECASE),
    # 检测 HTML 属性事件注入，当前仅限 onmouseover 和 onclick
    re.compile(r"on(?:mouseover|click)=", re.IGNORECASE),
    # 检测可能的 JavaScript 函数调用，如 eval(), setTimeout(), setInterval()
    re.compile(r"(eval\(|function\(|window\.)", re.IGNORECASE),
    # 检测 img 标签中的 onerror 属性
    re.compile(r"<img\s+[^>]*\s+onerror\s*=", re.IGNORECASE),
    # 检测带有 data: 协议的 JavaScript 或恶意数据载入
    re.compile(r"data\s*:\s*image\/*[a-zA-Z]*;base64,", re.IGNORECASE),
    # 检测 JavaScript 注入的锚标签：<a href="javascript:...">
    re.compile(r"href\s*=\s*\"javascript:", re.IGNORECASE),
    # 检测不良 HTML 标签注入，如 <object>, <iframe>, <form> 等
    re.compile(r"<(script|iframe|object|embed|form|input|img|svg|math|canvas|meta)[^>]*>", re.IGNORECASE),
    # 检测内联 JavaScript（例如，直接写在标签内的代码）
    re.compile(r"(document\.cookie|eval\(|setTimeout\(|setInterval\()"),
    # 捕捉任何含有 javascript: 的 HTML 属性值，防止注入
    re.compile(r"<([a-zA-Z]+)[^>]*\s+[^>]*=[^>]*javascript\s*:", re.IGNORECASE)
]

EMAIL_REGEX = re.compile(r"^[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+$")

ENUM_VALIDATION_RULES = {
    "require_email_update": {'Y', 'N'},
    "data_source": {'ALIPAY_DOCS', 'ALIPAY_DEV', 'FRONTEND_REVIEW'},
    "liked": {'dislike', 'like'},
    "model": {'gpt-3.5-turbo-16k-0613', 'gpt-3.5-turbo-1106', 'gpt-3.5-turbo-0125', 'gpt-4-1106-preview', 'gpt-4-0125-preview', 'gpt-4o-2024-05-13'},
    "tenant": {'PDS', 'ALIPAYPLUS', 'AMS', 'MINI', 'REMITTANCE'},
    "role": {'ACQP', 'MPP', 'PDS', 'REMITTANCE', 'MINI', 'All'}
}

def validate_input(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        app.logger.info(f"request is:{request}");

        content_type = request.headers.get('Content-Type')
        if content_type == 'application/json':
            request_body = request.get_json()
        elif content_type in ['application/x-www-form-urlencoded', 'multipart/form-data']:
            request_body = request.form.to_dict()
        else:
            request_body = {}
        if not request_body:
            app.logger.error('Request body is empty')
            return jsonify({'error': 'Invalid input data'}), 400

        # 检查 SQL 注入和 XSS 攻击
        for key, value in request_body.items():
            if isinstance(value, str):
                if any(pattern.search(value) for pattern in SQL_INJECTION_PATTERNS + XSS_PATTERNS):
                    app.logger.error(f'Suspected malicious content found in {key}')
                    return jsonify({'error': f'Suspected malicious content found in {key}'}), 400

        # 验证电子邮件格式
        email_fields = ["email", "user_email", "feedback_email"]
        for field in email_fields:
            if field in request_body and not EMAIL_REGEX.match(request_body[field]):
                app.logger.error(f'The format of the {field} is invalid')
                return jsonify({'error': f'The format of the {field} is invalid'}), 400

        # 验证枚举类型值
        for field, valid_values in ENUM_VALIDATION_RULES.items():
            if field in request_body and request_body[field] not in valid_values:
                app.logger.error(f'error:The value of parameter {field} is invalid')
                return jsonify({'error': f'The value of parameter {field} is invalid'}), 400

        # 确认 question_id 是数字
        if "question_id" in request_body:
            if not str(request_body["question_id"]).isdigit():
                app.logger.error(f'error:The value of parameter question_id is invalid')
                return jsonify({'error': 'The value of parameter question_id is invalid'}), 400

        return func(*args, **kwargs)
    return wrapper


if __name__ == '__main__':
    rs = find_relevant_knowledge_by_es(
        query_for_doc_retrieval='What is Alipay+?', db_table='knowledge_base', role='ACQP', version='1.3.5')
    for r in rs:
        print(r, end='\n\n')
